name: pre-commit

on:
  pull_request:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v7.0.0
      with:
        fetch-depth: 0
    - uses: actions/setup-python@v5
      with:
        python-version: "3.13"
    - uses: pre-commit/action@v3.0.1
      env:
        PRE_COMMIT_PR_BASE_SHA: ${{ github.event.pull_request.base.sha }}
        PRE_COMMIT_LIVE_BASE_REF: origin/${{ github.event.pull_request.base.ref }}
